# Generated by Django 3.2.4 on 2021-06-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('OldPrice', models.PositiveIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Features', models.TextField(max_length=150)),
                ('Description', models.TextField(max_length=1500)),
                ('ProductImage', models.ImageField(upload_to='products')),
                ('MainFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mainfeature')),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
        ),
    ]
