# Generated by Django 3.2.4 on 2021-06-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner')),
                ('alt_text', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '4. Home Page Banner',
            },
        ),
        migrations.AlterModelOptions(
            name='mainfeature',
            options={'verbose_name_plural': '1. Main Features'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name_plural': '3. Product Details'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': '2. Product Types'},
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
