# Generated by Django 3.2.4 on 2021-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.TextField(max_length=700)),
                ('ProductQty', models.IntegerField()),
                ('ProductPrice', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=40)),
                ('CustomerNumber', models.CharField(max_length=14)),
                ('CustomerAddress', models.TextField(max_length=150)),
                ('CustomerArea', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '5. Castomer Order',
            },
        ),
    ]
