# Generated by Django 3.2.4 on 2021-07-01 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210701_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.TextField(max_length=700)),
                ('ProductImage', models.CharField(max_length=1000)),
                ('ProductQty', models.CharField(max_length=100)),
                ('ProductPrice', models.CharField(max_length=100)),
                ('TotalPrice', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=40)),
                ('CustomerNumber', models.CharField(max_length=14)),
                ('CustomerArea', models.TextField(max_length=50)),
                ('CustomerAddress', models.TextField(max_length=150)),
                ('OrderDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': '5. Castomer Order',
            },
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
