# Generated by Django 3.2.4 on 2021-07-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210701_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrderr',
            new_name='ProductOrder',
        ),
    ]
