# Generated by Django 3.2.4 on 2021-07-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_productorderr_productorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': '2. Sub Menu'},
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductImage',
            field=models.ImageField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='ProductImage',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='SubMenuBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/subbanner')),
                ('FeatureName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mainfeature')),
            ],
            options={
                'verbose_name_plural': '3 Sub-menu Banner',
            },
        ),
    ]
