# Generated by Django 3.2.4 on 2021-07-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name_plural': '6. Home Page Banner'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name_plural': '5. Product Details'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name_plural': '7. Castomer Order'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='ContactWay',
            field=models.CharField(choices=[('ADDRESS', 'ADDRESS'), ('PHONE', 'PHONE'), ('EMAIL', 'EMAIL'), ('SERVING DAY', 'SERVING DAY')], max_length=50),
        ),
        migrations.CreateModel(
            name='Hotproducttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/hotproduct')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
            options={
                'verbose_name_plural': '3. Hot product Category',
            },
        ),
    ]
