# Generated by Django 3.2.4 on 2021-07-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210702_0417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productinfo',
        ),
    ]
