# Generated by Django 3.2.4 on 2021-07-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Hot', models.BooleanField(blank=True, default=True)),
                ('Discount', models.IntegerField(blank=True)),
                ('OldPrice', models.PositiveIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Features', models.TextField(max_length=150)),
                ('Description', models.TextField(max_length=1500)),
                ('ProductImage', models.ImageField(blank=True, upload_to='images/products')),
                ('ProductImage2', models.ImageField(blank=True, upload_to='images/products')),
                ('ProductImage3', models.ImageField(blank=True, upload_to='images/products')),
                ('ProductImage4', models.ImageField(blank=True, upload_to='images/products')),
                ('status', models.BooleanField(default=True)),
                ('MainFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mainfeature')),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
            options={
                'verbose_name_plural': '5. Product Details',
            },
        ),
    ]
