# Generated by Django 3.2.4 on 2021-07-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='Discount',
            field=models.TextField(blank=True, max_length=2),
        ),
    ]
