# Generated by Django 3.2.4 on 2021-07-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productinfo_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trend', models.CharField(max_length=50)),
                ('DiscountMessage', models.CharField(max_length=50)),
                ('startAmount', models.PositiveIntegerField()),
                ('EndAmount', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '5. Product Discount Info',
            },
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Discount',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
