# Generated by Django 3.2.4 on 2021-07-02 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210702_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=40)),
                ('CustomerNumber', models.CharField(max_length=14)),
                ('CustomerArea', models.CharField(max_length=50)),
                ('CustomerAddress', models.TextField(max_length=150)),
                ('Remark', models.TextField(max_length=150)),
                ('OrderDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('PaidStatus', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '8. Customer Order',
            },
        ),
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name_plural': '7. Home Page Banner'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name_plural': '6. Product Discount Info'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name_plural': '7.Order'},
        ),
        migrations.CreateModel(
            name='cartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=150)),
                ('item', models.CharField(max_length=150)),
                ('image', models.TextField(max_length=200)),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cartorder')),
            ],
            options={
                'verbose_name_plural': '9. Order Items',
            },
        ),
    ]
