# Generated by Django 3.2.4 on 2021-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210702_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='totalmount',
            field=models.IntegerField(default=0),
        ),
    ]
