# Generated by Django 3.2.4 on 2021-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_cartorder_totalmount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='totalmount',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
