# Generated by Django 3.2.4 on 2021-07-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_cartorder_totalmount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '9. Customer Order'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '10. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': '5 Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name_plural': '8. Home Page Banner'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name_plural': '7. Product Discount Info'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name_plural': '6. Product Details'},
        ),
    ]
